import Foundation

/// Convenience wrapper around `NSLocalizedString` that resolves keys from
/// `Bundle.module` — the bundle generated by Swift Package Manager when
/// resources are declared via `.process("Resources")` in `Package.swift`.
///
/// Using `Bundle.main` (the default for bare `NSLocalizedString` calls) does not
/// work in SPM-built executables because the `.strings` file lives in the module
/// bundle, not the main bundle. All UI code should call `L10n.string(_:)` instead
/// of `NSLocalizedString(_:comment:)` directly.
enum L10n {
    static func string(_ key: String, comment: String = "") -> String {
        NSLocalizedString(key, bundle: .module, comment: comment)
    }

    static func string(_ key: String, _ args: CVarArg..., comment: String = "") -> String {
        String(format: NSLocalizedString(key, bundle: .module, comment: comment), arguments: args)
    }
}
